version: '3'

dotenv: ['.env']

vars:
  DB_CONTAINER: postgres
  DB_USER: '{{.DB_USER | default "rbac"}}'
  DB_PASSWORD: '{{.DB_PASSWORD | default "rbac_password"}}'
  DB_NAME: '{{.DB_NAME | default "rbacdb"}}'

tasks:
  up:
    desc: Start containers
    cmds:
      - docker compose up -d

  down:
    desc: Stop containers
    cmds:
      - docker compose down

  migrate-up:
    desc: Apply all migrations
    cmds:
      - |
        set -euo pipefail
        for f in $(ls migrations/*.sql 2>/dev/null | grep -v '\.up\.sql$' | grep -v '\.down\.sql$' | sort); do
          echo "==> applying $f"
          cat "$f" | docker compose exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}} -v ON_ERROR_STOP=1
        done
        for f in $(ls migrations/*.up.sql 2>/dev/null | sort); do
          echo "==> applying $f"
          cat "$f" | docker compose exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}} -v ON_ERROR_STOP=1
        done

  migrate-down:
    desc: Rollback all migrations in reverse order
    cmds:
      - |
        set -euo pipefail
        for f in $(ls migrations/*.down.sql 2>/dev/null | sort -r); do
          echo "==> rolling back $f"
          cat "$f" | docker compose exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}} -v ON_ERROR_STOP=1
        done

  migrate-status:
    desc: Show migration status (list tables)
    cmds:
      - docker compose exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}} -c "SELECT tablename FROM pg_tables WHERE schemaname = 'public';"

  run:
    desc: Run service locally
    cmds:
      - go run ./cmd/ms-rbac-service

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...
