version: '3'

dotenv: ['.env', '../ms-go-user/.env']

vars:
  COMPOSE_FILE: '../ms-go-user/docker-compose.yml'
  DB_CONTAINER: postgres
  DB_USER: '{{.DB_USER | default "app"}}'
  DB_PASSWORD: '{{.DB_PASSWORD | default "app_password"}}'
  DB_NAME: '{{.RBAC_DB_NAME | default "rbacdb"}}'
  DB_SSLMODE: '{{.DB_SSLMODE | default "disable"}}'

tasks:
  create-db:
    desc: Create the RBAC database in shared Postgres (uses ms-go-user docker-compose)
    cmds:
      - |
        existing=$(docker compose -f {{.COMPOSE_FILE}} exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='{{.DB_NAME}}'")
        if [ -z "$existing" ]; then
          docker compose -f {{.COMPOSE_FILE}} exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d postgres -v ON_ERROR_STOP=1 -c "CREATE DATABASE {{.DB_NAME}}"
        fi

  migrate-up:
    desc: Apply RBAC migrations in order against the shared Postgres
    cmds:
      - task: create-db
      - |
        set -euo pipefail
        if [ -f migrations/001_init.sql ]; then
          echo "==> running migrations/001_init.sql"
          cat migrations/001_init.sql | docker compose -f {{.COMPOSE_FILE}} exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}}
        fi
        for f in $(ls migrations/*up.sql | sort); do
          echo "==> running $f"
          cat "$f" | docker compose -f {{.COMPOSE_FILE}} exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}}
        done

  migrate-down:
    desc: Roll back RBAC migrations in reverse order
    cmds:
      - |
        set -euo pipefail
        for f in $(ls migrations/*down.sql | sort -r); do
          echo "==> running $f"
          cat "$f" | docker compose -f {{.COMPOSE_FILE}} exec -T {{.DB_CONTAINER}} psql -U {{.DB_USER}} -d {{.DB_NAME}}
        done
